Tc 247 bug fnrfelt overlapper
navikt/veilarbportefoljeflatefs pull request #751
Opened 2022-09-21 13:49 UTC by klaramargrethehelgemo

Har oppdatert navds-pakkene til siste versjon. Rettet feil som oppsto i komponenten HelpText. Overlappfeilen er tenkt løst ved å lage en ny kolonnetype col-xs-2-5 med bredde 20%.

2022-09-21 14:28 UTC, Mathiamu requested changes

2022-09-21 14:28 UTC, Mathiamu commented on package.json
> +        "@navikt/ds-react-internal": "1.3.2",
Syns vi skal ha oppgradering til v1 i en egen PR, det er en del breaking changes 😅 
![bilde](https://user-images.githubusercontent.com/85442404/191531179-b787210b-76bf-458f-87cc-a433acc974e2.png)

2022-09-26 12:38 UTC, klaramargrethehelgemo commented on package.json
> +        "@navikt/ds-react-internal": "1.3.2",
Det er gjort.

2022-09-29 11:53 UTC, dragutin-nav approved these changes

2022-09-29 14:04 UTC, Mathiamu approved these changes

2022-09-29 14:05 UTC, merged